version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3"
  jobs:
    pre_install:
      - pip install mkdocs-material mkdocs-navsorted-plugin mkdocstrings[python]

mkdocs:
  configuration: mkdocs.yml

