site_name: uwsgiconf
site_url: !ENV READTHEDOCS_CANONICAL_URL

copyright: Copyright &copy; 2017-2025, Igor Starikov

repo_url: https://github.com/idlesign/uwsgiconf
edit_uri: edit/master/docs/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/idlesign

plugins:
  - search
  - navsorted

theme:
  name: material
  palette:
    primary: green
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.tab
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow

markdown_extensions:
  - mkdocs_apidescribed.extension
  - abbr
  - admonition
  - footnotes
  - md_in_html
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
