# Generated by Django 5.2.1 on 2025-06-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, db_column='dt_add', verbose_name='Created at')),
                ('dt_updated', models.DateTimeField(auto_now=True, db_column='dt_upd', verbose_name='Updated at')),
                ('name', models.TextField(unique=True, verbose_name='Name')),
                ('owner', models.TextField(blank=True, default='', verbose_name='Owner')),
                ('released', models.BooleanField(blank=True, db_index=True, default=True, verbose_name='Released')),
                ('dt_acquired', models.DateTimeField(blank=True, db_column='dt_acc', null=True, verbose_name='Acquired at')),
                ('dt_released', models.DateTimeField(blank=True, db_column='dt_rel', null=True, verbose_name='Released at')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Parameters')),
                ('result', models.JSONField(blank=True, default=dict, help_text='The previous run result.', verbose_name='Result')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'uwsgify_tasks',
            },
        ),
    ]
