# Generated by Django 5.2.2 on 2025-09-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwsgify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Active'),
        ),
    ]
