# Generated by Django 5.2.2 on 2025-12-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwsgify', '0002_task_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='active',
            field=models.BooleanField(blank=True, default=True, help_text='Task is available for the application to run. Use to temporarily disable runs.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dt_acquired',
            field=models.DateTimeField(blank=True, db_column='dt_acc', help_text='Date and time of the latest task run start.', null=True, verbose_name='Acquired at'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, db_column='dt_add', help_text='Task record registration date and time.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dt_released',
            field=models.DateTimeField(blank=True, db_column='dt_rel', help_text='Date and time of the latest task run finish.', null=True, verbose_name='Released at'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, db_column='dt_upd', help_text='Task record update date and time.', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.TextField(help_text='Task name. Coincides with a function name defined in the application code.', unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.TextField(blank=True, default='', help_text='Last owner of the task. By default a host name.', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='task',
            name='params',
            field=models.JSONField(blank=True, default=dict, help_text='Parameters passed to the task function.', verbose_name='Parameters'),
        ),
        migrations.AlterField(
            model_name='task',
            name='released',
            field=models.BooleanField(blank=True, db_index=True, default=True, help_text='Task is not currently running and is available for the application instance to acquire.', verbose_name='Released'),
        ),
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.JSONField(blank=True, default=dict, help_text='The result of the task function last run.', verbose_name='Result'),
        ),
    ]
